

project:
  type: website
  output-dir: docs
  resources: 
    - "*.pdf$"

website:
  title: "Braulio Güémez"
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    left:
      - icon: house
        text: about
        href: https://bguemez.github.io/

      - icon: file-person
        text: cv
        href: cv_july2026.pdf

      - icon: github
        text: github
        href: https://github.com/bguemez

      - icon: mortarboard-fill
        text: google scholar
        href: "https://scholar.google.com/citations?user=rV4FWTQAAAAJ&hl=en"


format:
  html:
    theme: [cosmo, styles.scss]
    fig-align: center
    code-fold: show
    grid:
      sidebar-width: 100px
      margin-width: 500px

execute:
  freeze: auto